name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name: Build
      run: |
        cd DomainBlocker
        mkdir -p build
        
        # 构建项目
        xcodebuild clean archive \
          -project DomainBlocker.xcodeproj \
          -scheme DomainBlocker \
          -configuration Release \
          -sdk iphoneos \
          -archivePath $PWD/build/DomainBlocker.xcarchive \
          PRODUCT_BUNDLE_IDENTIFIER="com.HengTai.Meng" \
          CODE_SIGN_STYLE=Manual \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          PROVISIONING_PROFILE_SPECIFIER="" \
          SKIP_INSTALL=NO \
          BUILD_LIBRARIES_FOR_DISTRIBUTION=YES \
          ENABLE_BITCODE=NO \
          COPY_PHASE_STRIP=NO \
          STRIP_INSTALLED_PRODUCT=NO
          
        # 准备 IPA 文件结构
        cd build
        rm -rf Payload
        mkdir -p Payload
        cp -r DomainBlocker.xcarchive/Products/Applications/DomainBlocker.app Payload/
        
        # 确保文件权限正确
        chmod -R 755 Payload
        
        # 创建 IPA
        rm -f DomainBlocker.ipa
        zip -qry DomainBlocker.ipa Payload
        
        # 验证 IPA 结构
        unzip -l DomainBlocker.ipa
      
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: DomainBlocker/build/DomainBlocker.ipa 