name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name: Build
      run: |
        cd DomainBlocker
        
        # 构建项目
        xcodebuild clean archive \
          -project DomainBlocker.xcodeproj \
          -scheme DomainBlocker \
          -configuration Release \
          -sdk iphoneos \
          -archivePath build/DomainBlocker.xcarchive \
          CODE_SIGN_STYLE=Manual \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          PROVISIONING_PROFILE_SPECIFIER="" \
          DEVELOPMENT_TEAM="V22J5U2YDA" \
          ENABLE_BITCODE=NO \
          COPY_PHASE_STRIP=NO \
          STRIP_INSTALLED_PRODUCT=NO \
          STRIP_SWIFT_SYMBOLS=NO \
          DEBUG_INFORMATION_FORMAT="dwarf-with-dsym"
        
        # 准备 IPA 文件结构
        cd build/DomainBlocker.xcarchive/Products/Applications/
        mkdir -p Payload
        cp -R DomainBlocker.app Payload/
        
        # 复制 Swift 运行时
        SWIFT_LIBS_PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos"
        mkdir -p Payload/DomainBlocker.app/Frameworks
        for lib in libswiftCore.dylib libswiftUIKit.dylib libswiftFoundation.dylib libswiftCoreFoundation.dylib libswiftDispatch.dylib libswiftObjectiveC.dylib libswiftDarwin.dylib libswiftCoreGraphics.dylib libswiftQuartzCore.dylib; do
          if [ -f "$SWIFT_LIBS_PATH/$lib" ]; then
            cp "$SWIFT_LIBS_PATH/$lib" Payload/DomainBlocker.app/Frameworks/
          fi
        done
        
        # 设置文件权限
        chmod -R 755 Payload
        find Payload -type f -exec chmod 644 {} \;
        find Payload -type d -exec chmod 755 {} \;
        
        # 创建 IPA
        zip -qry DomainBlocker.ipa Payload
        mv DomainBlocker.ipa ../../
        cd ../../
        
        # 显示 IPA 内容
        echo "IPA contents:"
        unzip -l DomainBlocker.ipa
      
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: DomainBlocker/build/DomainBlocker.ipa 